use super::targets::{HW_VALIDATION_TOLERANCE, SIGMA_MAX, SWAPTION_VEGA_FLOOR};
use super::*;

/// One contractual caplet/floorlet observation used to fit a scalar HW1F
/// short-rate volatility with fixed mean reversion.
///
/// Both the market and model prices are Bachelier prices in rate space.  The
/// model normal volatility is the product-specific unit-HW-sigma loading times
/// the scalar short-rate sigma.  Compounded-RFR callers supply their
/// date-specific moment-match loading; term-index callers may supply their
/// normal-vol loading while an exact bond-option calibration is unavailable.
#[derive(Debug, Clone, Copy)]
pub(crate) struct FixedKappaCapletPricePoint {
    /// Forward coupon rate under the contractual projection convention.
    pub forward: f64,
    /// Contractual cap/floor strike.
    pub strike: f64,
    /// Time to the contractual option fixing in years.
    pub option_time: f64,
    /// Discounted cashflow annuity, including notional when applicable.
    pub annuity: f64,
    /// Whether this point is a cap/call (`true`) or floor/put (`false`).
    pub is_cap: bool,
    /// Market normal volatility in absolute annual rate units.
    pub market_normal_vol: f64,
    /// Product-specific normal volatility generated by unit HW sigma.
    pub normal_vol_per_unit_sigma: f64,
}

impl FixedKappaCapletPricePoint {
    fn option_type(self) -> OptionType {
        if self.is_cap {
            OptionType::Call
        } else {
            OptionType::Put
        }
    }

    fn validate(self, index: usize, context: &str) -> finstack_quant_core::Result<()> {
        let fields = [
            ("forward", self.forward),
            ("strike", self.strike),
            ("option_time", self.option_time),
            ("annuity", self.annuity),
            ("market_normal_vol", self.market_normal_vol),
            ("normal_vol_per_unit_sigma", self.normal_vol_per_unit_sigma),
        ];
        for (name, value) in fields {
            if !value.is_finite() {
                return Err(finstack_quant_core::Error::Validation(format!(
                    "{context}: caplet point {index} has non-finite {name}={value}"
                )));
            }
        }
        if self.option_time <= 0.0
            || self.annuity <= 0.0
            || self.market_normal_vol <= 0.0
            || self.normal_vol_per_unit_sigma <= 0.0
        {
            return Err(finstack_quant_core::Error::Validation(format!(
                "{context}: caplet point {index} requires positive option_time, annuity, \
                 market_normal_vol, and normal_vol_per_unit_sigma"
            )));
        }
        Ok(())
    }

    fn market_price(self) -> f64 {
        bachelier_price(
            self.option_type(),
            self.forward,
            self.strike,
            self.market_normal_vol,
            self.option_time,
            self.annuity,
        )
    }

    fn model_price(self, sigma: f64) -> f64 {
        bachelier_price(
            self.option_type(),
            self.forward,
            self.strike,
            self.normal_vol_per_unit_sigma * sigma,
            self.option_time,
            self.annuity,
        )
    }

    fn market_vega(self) -> f64 {
        let std_dev = self.market_normal_vol * self.option_time.sqrt();
        if std_dev <= 0.0 {
            return 0.0;
        }
        let d = (self.forward - self.strike) / std_dev;
        self.annuity * self.option_time.sqrt() * norm_pdf(d)
    }
}

/// Solve the price-consistent scalar HW1F volatility for a fixed κ.
///
/// The target is the signed difference between the total product-consistent
/// HW-normal prices and the total Bachelier market prices.  For a long
/// cap/floor basket with positive vega this is monotonic in σ, making a
/// bracketed root both robust and auditable.  This is intentionally distinct
/// from averaging `market_vol / unit_sigma_loading`, which does not generally
/// reproduce prices for a heterogeneous schedule.
pub(crate) fn calibrate_fixed_kappa_sigma_to_caplet_prices(
    kappa: f64,
    points: &[FixedKappaCapletPricePoint],
    context: &str,
) -> finstack_quant_core::Result<f64> {
    if !kappa.is_finite() || kappa <= 0.0 {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: fixed HW1F kappa must be positive and finite, got {kappa}"
        )));
    }
    if points.is_empty() {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price calibration requires at least one caplet point"
        )));
    }
    for (index, point) in points.iter().copied().enumerate() {
        point.validate(index, context)?;
    }

    let market_price: f64 = points
        .iter()
        .copied()
        .map(FixedKappaCapletPricePoint::market_price)
        .sum();
    let market_vega: f64 = points
        .iter()
        .copied()
        .map(FixedKappaCapletPricePoint::market_vega)
        .sum();
    if !market_price.is_finite() || !market_vega.is_finite() || market_vega <= SWAPTION_VEGA_FLOOR {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price calibration has insufficient aggregate normal vega \
             ({market_vega:.6e})"
        )));
    }

    let residual = |sigma: f64| {
        points
            .iter()
            .copied()
            .map(|point| point.model_price(sigma))
            .sum::<f64>()
            - market_price
    };
    let lower = 1.0e-8;
    let upper = SIGMA_MAX;
    let lower_residual = residual(lower);
    let upper_residual = residual(upper);
    if !lower_residual.is_finite() || !upper_residual.is_finite() {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price calibration is non-finite at bracket \
             [{lower:.6e}, {upper:.6e}]"
        )));
    }
    if lower_residual.signum() == upper_residual.signum()
        && lower_residual != 0.0
        && upper_residual != 0.0
    {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price target is not bracketed on \
             [{lower:.6e}, {upper:.6e}]: residuals are \
             {lower_residual:.6e} and {upper_residual:.6e}"
        )));
    }

    let solver = BrentSolver::new().tolerance(1.0e-12).max_iterations(200);
    let sigma = solver.solve_in_bracket(residual, lower, upper)?;
    if sigma >= upper * (1.0 - 1.0e-6) {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price calibration hit the upper sigma bound {upper}"
        )));
    }
    let scaled_residual = residual(sigma).abs() / market_vega;
    if scaled_residual > HW_VALIDATION_TOLERANCE {
        return Err(finstack_quant_core::Error::Validation(format!(
            "{context}: scalar HW1F price calibration residual {scaled_residual:.6e} \
             exceeds tolerance {HW_VALIDATION_TOLERANCE:.6e}"
        )));
    }
    Ok(sigma)
}

/// `MarketContext` scalar-store keys for swaption-calibrated HW1F parameters.
///
/// Returns the `(kappa_key, sigma_key)` pair under which the swaption
/// Hull-White calibration step writes its solved κ/σ into the
/// [`MarketContext`](finstack_quant_core::market_data::context::MarketContext)
/// scalar store. The calibration writer and any downstream reader (e.g. the
/// HW1F pricer parameter resolver) must obtain these keys here so the
/// convention has a single source of truth and cannot drift.
///
/// # Examples
///
/// ```rust
/// use finstack_quant_valuations::calibration::hull_white::hw1f_scalar_keys;
///
/// let (kappa, sigma) = hw1f_scalar_keys("USD-OIS");
/// assert_eq!(kappa, "USD-OIS_HW1F_KAPPA");
/// assert_eq!(sigma, "USD-OIS_HW1F_SIGMA");
/// ```
///
/// # Arguments
///
/// * `curve_id` - Discount or projection curve identifier prefixed into the
///   returned mean-reversion and volatility scalar metric keys.
#[must_use]
pub fn hw1f_scalar_keys(curve_id: &str) -> (String, String) {
    (
        format!("{curve_id}_HW1F_KAPPA"),
        format!("{curve_id}_HW1F_SIGMA"),
    )
}

/// `MarketContext` scalar-store keys for cap/floor-calibrated HW1F parameters.
///
/// Returns the `(kappa_key, sigma_key)` pair under which the cap/floor
/// Hull-White calibration step writes its solved κ/σ into the
/// [`MarketContext`](finstack_quant_core::market_data::context::MarketContext)
/// scalar store. As with [`hw1f_scalar_keys`], this is the single source of
/// truth shared by the calibration writer and downstream readers.
///
/// # Examples
///
/// ```rust
/// use finstack_quant_valuations::calibration::hull_white::capfloor_hw1f_scalar_keys;
///
/// let (kappa, sigma) = capfloor_hw1f_scalar_keys("USD-OIS");
/// assert_eq!(kappa, "USD-OIS_CAPFLOOR_HW1F_KAPPA");
/// assert_eq!(sigma, "USD-OIS_CAPFLOOR_HW1F_SIGMA");
/// ```
///
/// # Arguments
///
/// * `curve_id` - Curve identifier prefixed into the returned cap/floor
///   mean-reversion and volatility scalar metric keys.
#[must_use]
pub fn capfloor_hw1f_scalar_keys(curve_id: &str) -> (String, String) {
    (
        format!("{curve_id}_CAPFLOOR_HW1F_KAPPA"),
        format!("{curve_id}_CAPFLOOR_HW1F_SIGMA"),
    )
}

/// Market-context series key for a cap/floor-calibrated piecewise HW1F sigma schedule.
///
/// # Arguments
///
/// * `curve_id` - Curve identifier prefixed into the returned cap/floor
///   time-dependent sigma schedule metric key.
#[must_use]
pub fn capfloor_hw1f_sigma_schedule_key(curve_id: &str) -> String {
    format!("{curve_id}_CAPFLOOR_HW1F_SIGMA_SCHEDULE")
}
