import * as wasm from '../../pkg/finstack_quant_wasm.js';

export const credit = {
  mertonModelJson: wasm.mertonModelJson,
  creditGradesModelJson: wasm.creditGradesModelJson,
  mertonDefaultProbability: wasm.mertonDefaultProbability,
  mertonDefaultProbabilityWithDrift: wasm.mertonDefaultProbabilityWithDrift,
  mertonDistanceToDefault: wasm.mertonDistanceToDefault,
  mertonDistanceToDefaultWithDrift: wasm.mertonDistanceToDefaultWithDrift,
  mertonKmvDefaultPoint: wasm.mertonKmvDefaultPoint,
  mertonImpliedSpread: wasm.mertonImpliedSpread,
  mertonDebtSpread: wasm.mertonDebtSpread,
  mertonCdsParSpread: wasm.mertonCdsParSpread,
  mertonFromEquityJson: wasm.mertonFromEquityJson,
  mertonFromCdsSpreadJson: wasm.mertonFromCdsSpreadJson,
  mertonFromTargetPdJson: wasm.mertonFromTargetPdJson,
  mertonModelWithDynamicsJson: wasm.mertonModelWithDynamicsJson,
  mertonTryImpliedEquity: wasm.mertonTryImpliedEquity,
  mertonToHazardCurveJson: wasm.mertonToHazardCurveJson,
  mertonSimulatePathsJson: wasm.mertonSimulatePathsJson,
  dynamicRecoveryAtNotional: wasm.dynamicRecoveryAtNotional,
  endogenousHazardAtLeverage: wasm.endogenousHazardAtLeverage,
  endogenousHazardAfterPikAccrual: wasm.endogenousHazardAfterPikAccrual,
  dynamicRecoveryConstantJson: wasm.dynamicRecoveryConstantJson,
  endogenousHazardPowerLawJson: wasm.endogenousHazardPowerLawJson,
  creditStateJson: wasm.creditStateJson,
  toggleExerciseThresholdJson: wasm.toggleExerciseThresholdJson,
  toggleExerciseOptimalJson: wasm.toggleExerciseOptimalJson,
};
