"""Audit public Rust contract types for effective serde and schema support."""

from .lexer import _cfg_condition_enabled, _split_top_level
from .models import (
    CAPABILITIES,
    CONTRACT_SUFFIXES,
    CURRENT_TARGET_ARCH,
    CURRENT_TARGET_IS_UNIX,
    CURRENT_TARGET_OS,
    NON_PRODUCT_CRATES,
    AuditConfigurationError,
    AuditReport,
    CrateSummary,
    Diagnostic,
    ExceptionEntry,
    PublicType,
    StaleException,
)
from .registries import (
    MAINTAINED_CONTRACTS,
    MAINTAINED_ONE_WAY_OUTPUTS,
    MAINTAINED_REQUIRED_CAPABILITIES,
    NON_MAINTAINED_SERDE_EXCEPTIONS,
    ONE_WAY_EXCEPTIONS,
    ONE_WAY_OUTPUT_IDENTITIES,
    REQUIRED_PUBLIC_TYPES,
    RESULT_ALIAS_EXCEPTIONS,
    REVIEWED_EXCEPTIONS,
    RUNTIME_RESULT_EXCEPTIONS,
)
from .report import build_parser, main, print_report
from .scanner import audit_workspace, scan_crate, scan_rust_file

__all__ = [
    "CAPABILITIES",
    "CONTRACT_SUFFIXES",
    "CURRENT_TARGET_ARCH",
    "CURRENT_TARGET_IS_UNIX",
    "CURRENT_TARGET_OS",
    "MAINTAINED_CONTRACTS",
    "MAINTAINED_ONE_WAY_OUTPUTS",
    "MAINTAINED_REQUIRED_CAPABILITIES",
    "NON_MAINTAINED_SERDE_EXCEPTIONS",
    "NON_PRODUCT_CRATES",
    "ONE_WAY_EXCEPTIONS",
    "ONE_WAY_OUTPUT_IDENTITIES",
    "REQUIRED_PUBLIC_TYPES",
    "RESULT_ALIAS_EXCEPTIONS",
    "REVIEWED_EXCEPTIONS",
    "RUNTIME_RESULT_EXCEPTIONS",
    "AuditConfigurationError",
    "AuditReport",
    "CrateSummary",
    "Diagnostic",
    "ExceptionEntry",
    "PublicType",
    "StaleException",
    "_cfg_condition_enabled",
    "_split_top_level",
    "audit_workspace",
    "build_parser",
    "main",
    "print_report",
    "scan_crate",
    "scan_rust_file",
]
